name = "ChemometricsTools"
uuid = "a9718f02-dbee-5ae5-ad0e-dfbd07fa387b"
authors = ["caseykneale "]
version = "0.5.8"

[deps]
Arpack = "7d9fca2a-8960-54d3-9f78-7d1dccf2cb97"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
DSP = "717857b8-e6f2-59f4-9121-6e50c889abd2"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"
HypothesisTests = "09f84164-cd44-5f33-b23f-e6b0d136a0d5"
IntervalArithmetic = "d1acc4aa-44c8-5952-acd4-ba5d80a2a253"
IntervalRootFinding = "d2bf35a9-74e0-55ec-b149-d360ff49b807"
LaTeXStrings = "b964fa9f-0449-5b57-a5c2-d3ea65f4040f"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
SpecialFunctions = "276daf66-3868-5448-9aa4-cd146d93841b"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "^1.0.0"
Arpack = "^0.3.1"
BenchmarkTools = "^0.4.3"
CSV = "^0.5.14"
DSP = "^0.6.0"
Combinatorics = "^0.7.0"
DataFrames = "^0.19.4"
Distributions = "^0.21.3"
FFTW = "^1.0.1"
HypothesisTests = "^0.8.0"
IntervalArithmetic = "^0.15.2"
IntervalRootFinding = "^0.4.0"
LaTeXStrings = "^1.0.3"
RecipesBase = "^0.7.0"
Revise = "^2.2.2"
Roots = "^0.8.3"
SpecialFunctions = "^0.7.2"
StaticArrays = "^0.11.1"
StatsBase = "^0.32.0"
